openfoodfacts/openfoodfacts-web

lang/en/texts/data.html

James Pan suggestions

---

lang/en/texts/index-pro.html

Eco-Score promo

---

lang/en/texts/data.html

fix: Add csv.gz

---

lang/en/texts/google-summer-of-code.html

- Update GSOC page with next steps and expectations

Update GSOC page with next steps and expectations

---

lang/en/texts/index-pro.html

- Add producer FAQ to the index-pro.html

feat: Add producer FAQ to the index-pro.html

---

lang/en/texts/data.html

doc: Add XML API example

---

README.md

- explain how to add or update a page

doc: explain how to add or update a page

---

crowdin.yml

- feat: Nutri-Score includes translatability

feat: Nutri-Score includes translatability

---

lang/en/texts/data.html

- fix: Fix changed facts on the data page

fix: Fix changed facts on the data page

---

lang/en/texts/eco-score-the-environmental-impact-of-food-products.html

feat: Refresh the ecoscore page with new visuals, better links and updated donation link

---

.github/labeler.yml
lang/obf/en/texts/data.html

- ci: add Info about the Open Beauty Facts API

ci: add Info about the Open Beauty Facts API

---

lang/en/texts/open-food-facts-mobile-app.html

- feat: install app blog URL changes

feat: install app blog URL changes

---

lang/en/texts/partners.html

- fix: update blog URLs on partners page

fix: update blog URLs on partners page

---

lang/en/texts/press.html

fix: fix blog in press page

---

lang/en/texts/nutriscore.html

- feat: add a openfoodfacts and the nutriscore promo

feat: add a openfoodfacts and the nutriscore promo

---

crowdin.yml
lang/en/texts/data.html
lang/obf/en/texts/data.html
lang/opf/en/texts/data.html
lang/opff/en/texts/data.html

- feat: Refresh the data pages for all projects

feat: Refresh the data pages for all projects

---

lang/en/texts/data.html

fix: API doc

---

lang/en/texts/discover.html

fix: logo max height

---

lang/en/texts/contribute.html

- feat: stub-special-operations

feat: Stub for special operations

---

crowdin.yml

fix: Add NOVA includes for translation

fix: Add NOVA includes for translation

---

.github/workflows/crowdin.yml

chore: Better Crowdin PR

---

lang/en/texts/terms-of-use.html

fix: typo in terms of use

---

lang/en/texts/data.html

Solves https://github.com/openfoodfacts/openfoodfacts-server/issues/8427.

fix: add section about downloading images in data.html

---

crowdin.yml

- fix: Make signup email translatable

fix: Make signup email translatable

---

lang/en/texts/index-pro.html

- Added the welcome video in the producers platform.
- 
-

feat: Adding welcome Video

---

lang/en/texts/nutriscore.html

feat: Official videos for Nutri-Score

---

lang/en/texts/dev-general.html

fix: accessibility-dev

---

lang/en/texts/mobile-app/features/additivesdetection.html
lang/en/texts/mobile-app/features/alternatives.html
lang/en/texts/mobile-app/features/contribute.html
lang/en/texts/mobile-app/features/cosmetics.html
lang/en/texts/mobile-app/features/darkmode.html
lang/en/texts/mobile-app/features/environmentalscoring.html
lang/en/texts/mobile-app/features/fooddecyphering.html
lang/en/texts/mobile-app/features/history.html
lang/en/texts/mobile-app/features/holidays.html
lang/en/texts/mobile-app/features/hungergames.html
lang/en/texts/mobile-app/features/journeytofoodknowledge.html
lang/en/texts/mobile-app/features/lowsaltfatsugar.html
lang/en/texts/mobile-app/features/mapoffoodfactories.html
lang/en/texts/mobile-app/features/monitoryourcontributions.html
lang/en/texts/mobile-app/features/nutritionalscoring.html
lang/en/texts/mobile-app/features/nutritionforportions.html
lang/en/texts/mobile-app/features/offlinemode.html
lang/en/texts/mobile-app/features/originsofingredients.html
lang/en/texts/mobile-app/features/packaging.html
lang/en/texts/mobile-app/features/privatebydesign.html
lang/en/texts/mobile-app/features/readinessscore.html
lang/en/texts/mobile-app/features/scan.html
lang/en/texts/mobile-app/features/search.html
lang/en/texts/mobile-app/features/ultraprocessing.html
lang/en/texts/mobile-app/features/veganvegetarianpalmoilchecker.html

fixes to images

---

lang/en/texts/open-food-facts-mobile-app.html

New landing page for mobile app based on @manon-corneille 's work.
It looks like this:
edit: I've updated the screenshot after the fixes.

feat: add a landing page for the mobile app

---

lang/en/texts/data.html

feat: revamp the Data page

---

lang/en/texts/nutriscore.html

- feat: update Nutri-Score based on SpF recos

feat: update Nutri-Score based on SpF recos

---

lang/en/texts/terms-of-use.html

- feat: legal-and-privacy-emails

feat: legal-and-privacy-emails

---

lang/en/texts/follow-open-food-facts.html

- feat: follow-open-food-facts.html
- Related Wiki page: https://wiki.openfoodfacts.org/Public_Relations/Social_Media_accounts

feat: follow-open-food-facts.html

---

lang/en/texts/privacy.html

- fix: fixes for issues spotted by @galnaf in privacy.html

fix: fixes for issues spotted by @galnaf in privacy.html

---

.github/workflows/preprod-deploy.yml

So that off-web changes are visible

ci: restart staging backend on deploy

---

lang/en/texts/eco-score-the-environmental-impact-of-food-products.html

fix: Broken image  fixes #518

---

lang/obf/it/texts/chi-siamo.html
lang/obf/it/texts/codice-di-condotta.html
lang/obf/it/texts/contribuire.html
lang/obf/it/texts/partner.html
lang/obf/it/texts/scopri.html
lang/obf/it/texts/stampa.html

Symbolic links for Italian pages
#541

fix: OBF Symbolic links Italian

---

lang/obf/en/texts/logos.html

- feat: logos for Open Beauty Facts

feat: logos for Open Beauty Facts

---

lang/en/texts/contribute.html

- feat: Change the URL of the skill pool to the new form powered by our Odoo instance

feat: Change the URL of the skill pool to the new form powered by our Odoo instance

---

lang/en/texts/cop26/blocks/ecoscore-app-install.html

- feat: ecoscore app promo fixes + QRCODE

feat: Eco-Score app promo fixes + QRCODE

---

lang/en/texts/processing/mobile-app-promo-processing.html

feat: NOVA QR code promo

---

lang/en/texts/nutriscore/mobile-app-promo-nutriscore.html

- feat: add QRCode to Nutri-Score page

feat: add QRCode to Nutri-Score page

---

lang/en/texts/nova.html

- doc: Add a link to the NOVA FAQ

docs: Add a link to the NOVA FAQ

---

knowledge_panels/README.md

feat: README for additives

---

lang/en/texts/data.html

fix: add repos

---

lang/en/texts/data.html

- Add [DuckDB-URL ](https://blog.openfoodfacts.org/en/news/food-transparency-in-the-palm-of-your-hand-explore-the-largest-open-food-database-using-duckdb-%f0%9f%a6%86x%f0%9f%8d%8a) to OFF Data webpage

docs(duckdb-url): :sparkles: Add DuckDB x OFF blog post url to data.html

---

.github/workflows/github-projects.yml

ci: Update github-projects.yml

---

lang/en/texts/nutriscore.html

docs: Nutri-Score FAQ

---

lang/obf/en/texts/data.html
lang/opff/en/texts/data.html

feat: obf-data-reload

---

lang/opf/en/texts/data.html

feat: reboot OPF data page

---

knowledge_panels/ingredients/world-en.yml
knowledge_panels/ingredients/world-fr.yml
lang/fr/knowledge_panels/ingredients/en_corn-syrup_fr.html
lang/fr/knowledge_panels/ingredients/en_corn-syrup_world.html

fix: ingredients content yaml fix

---

.github/workflows/label.yml

fix: Update label.yml

---

lang/fr/texts/faq.html

Our uservoice account has been deleted as they removed the free accounts.

fix: remove uservoice links

---

lang/en/texts/follow-open-food-facts.html

- feat: Update follow-open-food-facts.html

feat: Update follow-open-food-facts.html

---

lang/en/texts/who-we-are.html

- feat: add-new-social-networks to who-we-are.html

feat: add-new-social-networks to who-we-are.html

---

lang/fr/texts/new-nutriscore.html

ci: Move domain to dot org

---

lang/en/texts/open-food-facts-mobile-app.html

- fix: green-score-fix-for-app

fix: green-score-fix-for-app

---

lang/obf/en/texts/data.html

- the next step is there: https://github.com/openfoodfacts/openfoodfacts-exports/issues/27

feat: Parquet for Open Beauty Facts

---

lang/en/texts/new-nutriscore.html

- ci: nutriscore-v2-update to reflect the signature of the French decree

ci: nutriscore-v2-update to reflect the signature of the French decree

---

knowledge_panels/prompts.txt

- feat: Create prompts.txt for knowledge panels draft generation

feat: Create prompts.txt for knowledge panels draft generation

---

crowdin-kp.yml

- fix: Knowledge Panels catchall
- alternative to https://github.com/openfoodfacts/openfoodfacts-web/pull/707

fix: Knowledge Panels catchall

---

lang/en/texts/nutriscore/nutriscore-new-formula-presskit.html

- feat: Create nutriscore-new-formula-presskit.html
TODO
- Replace .net by .org
- Check that all variants show the new computation banner
- Understand how we can easily fetch officially translated logos

feat: Create nutriscore-new-formula-presskit.html

---

lang/opff/en/texts/index.html

feat: update Pet food index

---

lang/obf/en/texts/index.html

feat: Cosmetic index
